"""add_date_and_name_to_menus

Revision ID: 4105d1e2a3a9
Revises: 3351ba47dbb2
Create Date: 2018-03-10 19:23:46.612792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4105d1e2a3a9'
down_revision = '3351ba47dbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('menu', sa.Column('name', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_menu_date'), 'menu', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_date'), table_name='menu')
    op.drop_column('menu', 'name')
    op.drop_column('menu', 'date')
    # ### end Alembic commands ###
